language: node_js
sudo: required
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache: yarn
notifications:
  email: false
node_js:
  - 'lts/*'
before_install: yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
  - npm run generate
script:
  - npm run test:prod
  - npm run build
after_success:
  - greenkeeper-lockfile-upload
  - npm run report-coverage
before_deploy:
  - npm run prepare-doc
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    local-dir: dist/docs
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release
    on:
      branch: master
